server:
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: notification-service-k3s
  data:
    redis:
      host: ${REDIS_ENDPOINT}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_ENDPOINT}
    client-id: ${CLIENT_ID}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: ${GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
    admin:
      fail-fast: true
logging:
  level:
    org:
      springframework:
        data:
          redis: debug
    io:
      lettuce:
        core: debug
app:
  redis:
    key: ${REDIS_KEY}
    ttl: ${REDIS_TTL}
  kafka:
    topic: ${KAFKA_TOPIC}
    group-id: ${KAFKA_GROUP_ID}
