spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    org:
      springframework:
        data:
          redis: debug
    io:
      lettuce:
        core: debug
app:
  redis:
    key: test.notification:eventId
    ttl: 1
  kafka:
    topic: "test.notifications.register-events.v1"
    group-id: "notification-service"